# config for training

trainer:
  checkpoint: "./tune/2spk_dcnet_d"
  optimizer: "rmsprop"
  lr: 0.00001
  momentum: 0.9
  weight_decay: 0
  clip_norm: 200
  num_spks: 2

dcnet:
  rnn: "lstm"
  embedding_dim: 20
  num_layers: 2
  hidden_size: 600
  dropout: 0.5
  non_linear: "tanh"
  bidirectional: true

spectrogram_reader:
  frame_shift: 64
  frame_length: 256
  window: "hann"
  transpose: true
  apply_log: true
  apply_abs: true

train_scp_conf:
  mixture: "./data/2spk/train/wav8k_min_mix.scp"
  spk1: "./data/2spk/train/wav8k_min_s1.scp"
  spk2: "./data/2spk/train/wav8k_min_s2.scp"

valid_scp_conf:
  mixture: "./data/2spk/dev/wav8k_min_mix.scp"
  spk1: "./data/2spk/dev/wav8k_min_s1.scp"
  spk2: "./data/2spk/dev/wav8k_min_s2.scp"

debug_scp_conf:
  mixture: "./data/2spk/test/wav8k_min_mix.scp"
  spk1: "./data/2spk/test/wav8k_min_s1.scp"
  spk2: "./data/2spk/test/wav8k_min_s2.scp"
  
#train_scp_conf:
#  mixture: "./data/2spk/train/mix.scp"
#  spk1: "./data/2spk/train/spk1.scp"
#  spk2: "./data/2spk/train/spk2.scp"

#valid_scp_conf:
#  mixture: "./data/2spk/dev/mix.scp"
#  spk1: "./data/2spk/dev/spk1.scp"
#  spk2: "./data/2spk/dev/spk2.scp"

#debug_scp_conf:
#  mixture: "./data/tune/mix.scp"
#  spk1: "./data/tune/spk1.scp"
#  spk2: "./data/tune/spk2.scp"

dataloader:
  shuffle: true
  batch_size: 1
  drop_last: false
  vad_threshold: 40
